"""new fields in user model

Revision ID: 17404d501f26
Revises: ac2be730681f
Create Date: 2021-12-06 17:19:36.525890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17404d501f26'
down_revision = 'ac2be730681f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
