"""user tokens

Revision ID: 32df90c95255
Revises: 2c28d9ed3da6
Create Date: 2021-12-17 13:45:41.652309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32df90c95255'
down_revision = '2c28d9ed3da6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('token', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('token_expiration', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_token'), 'user', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_token'), table_name='user')
    op.drop_column('user', 'token_expiration')
    op.drop_column('user', 'token')
    # ### end Alembic commands ###
