"""add language to posts

Revision ID: 037a69b9d1e5
Revises: 644fddce731e
Create Date: 2021-12-10 08:58:15.401266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '037a69b9d1e5'
down_revision = '644fddce731e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
